### ISSUE TITLE
Portfolio artifacts

### ISSUE THREAD

**Issue by KonnerPierce** [CaptFizzo/NClohessy.github.io#1]
Maybe give your artifact area more space under your photo so that you can have an image or video for each artifact so that people will look at it and think "oh that looks cool" and want to check it out. Like a clickbait youtube thumbnail lol.

**Comment by CaptFizzo** [comment]
Adjusted layout to provide more room for eventual artifact updates. Still narrowing down the exact artifacts in question, so space may change slightly as uploads continue
